version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "8080:443"
    links:
      - php
  php:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    links:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
  mysql:
    image: mysql:5.7
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=beejeetest"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_DATABASE=beejeetest"
    ports:
      - "33061:3306"
    tty: true
